### ISSUE TITLE
how to register new client-ids and subscription (with open source version)

### ISSUE THREAD

**Issue by rohgoyal** [strongloop/microgateway#103]
Hi, I have downloaded the open source version of Microgateway and created a Swagger yaml with SecurityDefinitions

```
securityDefinitions:
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
```

I was able to call the API with following curl command
`curl http://localhost:3000/trial/echo -H "X-IBM-Client-Id:default"`

I wanted to find out how can I register more specific client ids with Microgateway?
